Step 1:Import dependencies 

In [3]:
%pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [5]:
%pip install "stable-baselines3[extra]"
%pip install gymnasium 




Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [6]:
# Install the gym module if not already installed
import os
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


2. Load env. 


In [7]:
environment_name = 'CartPole-v0'
env = gym.make(environment_name)
environment_name


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gymnasium/envs/registration.py:512: DeprecationWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.deprecation(


'CartPole-v0'

In [9]:
#testing the environment
episodes = 5
for episode in range(0, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, truncated, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Episode:0 Score:12.0
Episode:1 Score:19.0
Episode:2 Score:18.0
Episode:3 Score:44.0
Episode:4 Score:19.0
Episode:5 Score:18.0


In [10]:
episode = 5
for episode in range (1, episode +1): 
    print(episode)

1
2
3
4
5


In [11]:
env.step(1)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/gymnasium/envs/classic_control/cartpole.py:214: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


(array([ 0.24415095,  0.95306647, -0.2586402 , -1.6226442 ], dtype=float32),
 0.0,
 True,
 False,
 {})

In [12]:
env.observation_space.sample()

array([-3.7981853 ,  0.85780305,  0.18822442,  0.77470315], dtype=float32)

Understanding the enviornment.

In [13]:
env.action_space

Discrete(2)

In [14]:
env.action_space.sample()

np.int64(0)

In [15]:
env.observation_space

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)

In [16]:
env.observation_space.sample()

array([-1.0779622 ,  0.7088075 ,  0.39837852,  1.0783874 ], dtype=float32)

3. TRAINING

In [ ]:
log_path = os.path.join('Training', 'Logs')